### PR TITLE
Use encodeURIComponent to ensure all special characters in the query are escaped

### PR DESCRIPTION
**Pull request by joein3d**
Previously + was not being escaped causing it to be treated as a space in queries.

### CODE REVIEW

**Comment by coryalder** [comment]
Just noticed this as well, came here to report the issue. Glad it's been fixed!

**Comment by kLy** [comment]
When will this get merged? It causes quite a bit of issues when trying to search for things like "C#"

**Comment by arnemart** [comment]
Sorry about being super slow here, I've been on a really long vacation. This will be merged and a new release made Very Shortly™.

**Comment by kLy** [comment]
Any word on this? :)

**Comment by arnemart** [comment]
Oh man I am super sorry. Completely forgot about this. Merging and making the release right now.

**Comment by kLy** [comment]
Woo! :)

**Pull request merged**
