### PR TITLE
Fix spelling and remove unnecessary word

### PR DESCRIPTION
**Pull request by KovuTheHusky**
Fix spelling and remove unnecessary word

### CODE REVIEW

**Comment by KovuTheHusky** [comment]
Is this a wontfix or something else?

**Comment by arnemart** [comment]
Wontfix. I appreciate you making the effort, but to be frank this pull request seems kind of pointless. No offence intended.

**Comment by KovuTheHusky** [comment]
Alright. I just don't see why you'd prefer the message misspelled. Thanks for your work on the extension. I've been using it for months now.

**Comment by arnemart** [comment]
Oh, dude, after reading the diff for the 10th time I just realized that there was an actual misspelling there. I thought you had just removed the word “like”. A thousand pardons.

**Comment by KovuTheHusky** [comment]
It's easy to have your eye fix errors before they hit your brain. Thanks for the pull!

**Pull request merged**
